### PR TITLE
Emergencystop

### PR DESCRIPTION
**Pull request by sbman**
Added emergency stop feature. Automatically stops run if the temp sensor stops reporting data.

### CODE REVIEW

**Comment by chron0** [comment]
Sweet, thanks, as soon as the new lab is online again, another sprint will be focusing on picoReflow to test and extend more features/safety/usability

**Comment by sbman** [comment]
I've also created a python web client that displays oven data on an
Adafruit 16x2 lcd and enables to switches to start/stop the oven and choose
profiles. I need to clean it up a bit, but I can post a repo on github.

**Comment by chron0** [comment]
Even though I personally try to avoid any auxiliary displays and UIs other than mobile (android) and laptop/monitor/computer to reduce environmental per person footprint (hence the trend to make things as web apps), I'm always happy to see people hack other solutions to fit their particular needs, so by all means, clean or unclean, please publish it, I'm sure it will be of some use to someone else and will enrich picoreflow/picopid use cases.

**Comment by sbman** [comment]
I'm running the display on the same Raspberry Pi that picoReflow runs on. I
coded it as a web client to decouple it from the reflow project, it just
connects to picoReflow @ localhost.  The LCD and switches mounted on the
front of the oven gives it a nice finished look and users can run a profile
right from the front panel.

**Pull request merged**
